### ISSUE TITLE
No corre npm start

### ISSUE THREAD

**Issue by ProjectCOR** [goldesjuan/sopa-de-letras#1]
Hola @goldesjuan como estas?
No pudimos hacerlo correr.  te paso el error:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/12.11.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.7.0
3 info using node@v11.15.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle sopa-de-letras@1.0.0~prestart: sopa-de-letras@1.0.0
6 info lifecycle sopa-de-letras@1.0.0~start: sopa-de-letras@1.0.0
7 verbose lifecycle sopa-de-letras@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle sopa-de-letras@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/gabrielrmarin/www/tests/juangoldes/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands
9 verbose lifecycle sopa-de-letras@1.0.0~start: CWD: /Users/gabrielrmarin/www/tests/juangoldes
10 silly lifecycle sopa-de-letras@1.0.0~start: Args: [ '-c', 'node ./src/index.js' ]
11 silly lifecycle sopa-de-letras@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle sopa-de-letras@1.0.0~start: Failed to exec start script
13 verbose stack Error: sopa-de-letras@1.0.0 start: `node ./src/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:999:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid sopa-de-letras@1.0.0
15 verbose cwd /Users/gabrielrmarin/www/tests/juangoldes
16 verbose Darwin 19.4.0
17 verbose argv "/usr/local/Cellar/node/12.11.1/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v11.15.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error sopa-de-letras@1.0.0 start: `node ./src/index.js`
22 error Exit status 1
23 error Failed at the sopa-de-letras@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by goldesjuan** [comment]
@ProjectCOR probá con una versión más nueva de Node (12 o superior), la versión lts actual es la 12.18.1.
Para cambiar rápido de versión podés instalar [n](https://github.com/tj/n) que es un version manager de Node.
